version: '3.3'
services:
    rabbitmq:
       image: keerthibalan/rabbitmq:3.8.12
       container_name: rabbitmq_official
       ports:
         - 5672:5672
         - 15672:15672
       expose:
         - "5672"
         - "15672"
       networks:
         - server
networks:
  server:
    driver: bridge
volumes:
    networks:

